--GROUP BY 절
--그룹의 기준을 작성하는 절
SELECT DEPT_CODE, SALARY
FROM EMPLOYEE
ORDER BY DEPT_CODE;

SELECT DEPT_CODE, SUM(SALARY), COUNT(*), TRUNC(AVG(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--EMPLOYEE 테이블에서 부서코드, 보너스를 지급받는 사원 수를 조회하고 
--부서코드 순으로 정렬하세요
SELECT DEPT_CODE, COUNT(*)
FROM EMPLOYEE
WHERE BONUS IS NOT NULL
GROUP BY DEPT_CODE;

--직급별 평균 급여를 조회하시오
--직급, 급여합, 인원수, 평균급여(소수점 이하는 내림 처리)
SELECT JOB_CODE, SUM(SALARY), COUNT(*), FLOOR(AVG(SALARY))
FROM EMPLOYEE
GROUP BY JOB_CODE;

--성별로 구분하여 급여합, 인원수, 평균급여 조회(소숫점 2째자리 까지 반올림 표기)
SELECT DECODE(SUBSTR(EMP_NO, 8, 1),1,'남',2,'여') AS "성별", SUM(SALARY), COUNT(*), ROUND(AVG(SALARY),2) AS "평균급여"
FROM EMPLOYEE
GROUP BY SUBSTR(EMP_NO, 8, 1);

--부서별, 직급별 급여의 합계를 구하시오
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE;

--부서별, 직급별 급여의 합계가 800만원 이상인, 
--부서와 직급, 급여의 합계를 출력
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE
HAVING 8000000 <= SUM(SALARY);


--직원이 5명이상인 부서의 부서코드, 직원수를 출력하시오
--단, 직원수가 많은 순으로 출력
SELECT DEPT_CODE, COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING 5 <= COUNT(*);


--태어난 년도 별로(10년 단위) 그룹을 나누었을때, 
--년도,년도 별 인원이 몇명인지, 해당 년도의 평균급여는 얼마 인지 출력
--평균급여는 소숫점 이하 버림 
SELECT TO_NUMBER(SUBSTR(EMP_NO,1,1)) * 10 AS "년대", COUNT(*), TRUNC(AVG(SALARY))
FROM EMPLOYEE
GROUP BY SUBSTR(EMP_NO,1,1);

--SELECT         5
--FROM            1
--WHERE          2
--GROUP BY    3
--HAVING         4
--ORDER BY    6


SELECT DEPT_CODE, SUM(SALARY), GROUPING(DEPT_CODE)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE);

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY), GROUPING(DEPT_CODE), GROUPING(JOB_CODE)
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE);


SELECT DEPT_CODE, SUM(SALARY), GROUPING(DEPT_CODE) "집계여부"
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE)
ORDER BY "집계여부";

SELECT DEPT_CODE, JOB_CODE, SUM(SALARY), GROUPING(DEPT_CODE)"직책별집계", GROUPING(JOB_CODE)"부서별집계"
FROM EMPLOYEE
GROUP BY CUBE(DEPT_CODE, JOB_CODE)
ORDER BY "직책별집계", "부서별집계";

--D5, D6, D9의 부서별, 직급별 급여의 합을 구하여라
--집계함수를 사용하여 총합도 표시(ROLLUP)
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D6', 'D9')
GROUP BY ROLLUP(DEPT_CODE, JOB_CODE);


--D5, D6, D9의 부서별, 직급별 급여의 합을 구하여라
--집계함수를 사용하여 총합도 표시(CUBE)
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY), GROUPING(DEPT_CODE), GROUPING(JOB_CODE)
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5', 'D6', 'D9')
GROUP BY CUBE(DEPT_CODE, JOB_CODE);






SELECT DEPT_CODE, JOB_CODE, SUM(SALARY), GROUPING(DEPT_CODE), GROUPING(JOB_CODE)
FROM EMPLOYEE
WHERE DEPT_CODE IN ('D5','D6','D9')
GROUP BY CUBE(DEPT_CODE, JOB_CODE);








